export const initialState = {
  categories: [
    {
      id: 'hats',
      name: 'Hats',
    },
    {
      id: 'mugs',
      name: 'Mugs',
    },
    {
      id: 'tshirts',
      name: 'T-shirts',
    },
  ],
  products: [
    {
      id: '1',
      name: 'Hat Aqua',
      desc: 'Aliquam massa arcu, porta eu justo eget, venenatis congue leo. Sed at risus et ipsum euismod volutpat non in velit.',
      category: 'hats',
      price: 19,
      image: 'src=../../images/Products/hats/hatAqua.png',
      sale: true,
      featured: false,
    },
    {
      id: '2',
      name: 'Hat Blue',
      desc: 'Praesent faucibus nisi eget convallis finibus. Donec lobortis risus enim, sit amet faucibus quam elementum nec. Donec porttitor et nulla.',
      category: 'hats',
      price: 29,
      image: 'src=../../images/Products/hats/hatBlue.png',
      sale: false,
      featured: true,
    },
    {
      id: '3',
      name: 'Hat Green',
      desc: 'Integer id ornare mi. Vestibulum imperdiet ac tortor ac hendrerit. Sed ullamcorper purus a turpis lacinia vestibulum. Cras eleifend malesuada.',
      category: 'hats',
      price: 19,
      image: 'src=../../images/Products/hats/hatGreen.png',
      sale: false,
      featured: false,
    },
    {
      id: '4',
      name: 'Hat Grey',
      desc: 'Pellentesque non fermentum tellus, vulputate porttitor est. Integer mattis vitae sapien a pretium. Quisque elementum et ipsum non consectetur. Aenean.',
      category: 'hats',
      price: 39,
      image: 'src=../../images/Products/hats/hatGrey.png',
      sale: true,
      featured: false,
    },
    {
      id: '5',
      name: 'Hat Orange',
      desc: 'Curabitur eu massa quis ex feugiat egestas. Fusce non ultrices sem. In sed faucibus arcu. Aliquam semper, nisl vel rutrum.',
      category: 'hats',
      price: 19,
      image: 'src=../../images/Products/hats/hatOrange.png',
      sale: false,
      featured: false,
    },
    {
      id: '6',
      name: 'Hat Purple',
      desc: 'Fusce in dui a risus accumsan volutpat. Quisque convallis ipsum sit amet nulla gravida, in consectetur ligula sagittis. Maecenas imperdiet.',
      category: 'hats',
      price: 29,
      image: 'src=../../images/Products/hats/hatPurple.png',
      sale: false,
      featured: true,
    },
    {
      id: '7',
      name: 'Hat Red',
      desc: 'Sed pretium interdum magna, ut molestie massa varius non. Quisque vitae orci quis mauris facilisis luctus. Nam sed faucibus quam.',
      category: 'hats',
      price: 49,
      image: 'src=../../images/Products/hats/hatRed.png',
      sale: false,
      featured: false,
    },
    {
      id: '8',
      name: 'Hat White',
      desc: 'Mauris ac ante egestas, scelerisque nunc a, pellentesque velit. Nunc imperdiet nisl sem, vel pretium mauris tempor vel. Nunc pretium.',
      category: 'hats',
      price: 39,
      image: 'src=../../images/Products/hats/hatWhite.png',
      sale: false,
      featured: false,
    },
    {
      id: '9',
      name: 'Hat Yellow',
      desc: 'Praesent tincidunt ipsum ultricies tellus tincidunt, sit amet laoreet libero laoreet. Sed leo dolor, hendrerit quis imperdiet ut, accumsan nec.',
      category: 'hats',
      price: 39,
      image: 'src=../../images/Products/hats/hatYellow.png',
      sale: false,
      featured: false,
    },
    {
      id: '10',
      name: 'Mug Aqua',
      desc: 'Donec eu vestibulum nisl, pellentesque efficitur sem. Phasellus et urna id velit fringilla accumsan. Praesent tempus neque tellus, et semper.',
      category: 'mugs',
      price: 19,
      image: 'src=../../images/Products/mugs/mugAqua.png',
      sale: true,
      featured: false,
    },
    {
      id: '11',
      name: 'Mug Blue',
      desc: 'Proin porta lobortis molestie. Mauris felis tellus, fringilla a ligula sed, scelerisque maximus ante. Fusce finibus arcu mattis congue molestie.',
      category: 'mugs',
      price: 29,
      image: 'src=../../images/Products/mugs/mugBlue.png',
      sale: false,
      featured: true,
    },
    {
      id: '12',
      name: 'Mug Green',
      desc: 'Vivamus nec vulputate metus. Maecenas rhoncus mauris non odio consequat bibendum. Duis blandit sagittis enim, at sodales eros pulvinar id.',
      category: 'mugs',
      price: 19,
      image: 'src=../../images/Products/mugs/mugGreen.png',
      sale: false,
      featured: true,
    },
    {
      id: '13',
      name: 'Mug Grey',
      desc: 'Mauris et ex eget quam vulputate tempus eu sit amet tellus. Maecenas sagittis fringilla enim, eget sagittis arcu sodales vitae.',
      category: 'mugs',
      price: 29,
      image: 'src=../../images/Products/mugs/mugGrey.png',
      sale: false,
      featured: false,
    },
    {
      id: '14',
      name: 'Mug Orange',
      desc: 'Praesent tincidunt dui ut libero placerat auctor. Proin quis vulputate mi. Quisque laoreet diam eu augue rutrum mattis. Curabitur gravida.',
      category: 'mugs',
      price: 19,
      image: 'src=../../images/Products/mugs/mugOrange.png',
      sale: true,
      featured: false,
    },
    {
      id: '15',
      name: 'Mug Purple',
      desc: 'In hac habitasse platea dictumst. Fusce in lectus eleifend, efficitur elit sed, congue nibh. Nunc a nunc est. Aenean dictum.',
      category: 'mugs',
      price: 29,
      image: 'src=../../images/Products/mugs/mugPurple.png',
      sale: false,
      featured: false,
    },
    {
      id: '16',
      name: 'Mug Red',
      desc: 'Sed sed nisi vel tellus maximus ultricies eget lacinia metus. Donec a ipsum quis orci vulputate bibendum. Quisque in mauris.',
      category: 'mugs',
      price: 19,
      image: 'src=../../images/Products/mugs/mugRed.png',
      sale: false,
      featured: false,
    },
    {
      id: '17',
      name: 'Mug White',
      desc: 'Aenean consequat dui eu dui aliquet malesuada. Ut porta nisl a risus iaculis, vitae congue dolor bibendum. In hac habitasse.',
      category: 'mugs',
      price: 29,
      image: 'src=../../images/Products/mugs/mugWhite.png',
      sale: false,
      featured: false,
    },
    {
      id: '18',
      name: 'Mug Yellow',
      desc: 'Donec nec augue molestie, posuere lacus sit amet, vulputate tortor. Nunc eleifend pellentesque euismod. Nam condimentum elit at mauris sagittis.',
      category: 'mugs',
      price: 19,
      image: 'src=../../images/Products/mugs/mugYellow.png',
      sale: false,
      featured: false,
    },
    {
      id: '19',
      name: 'T-shirt Aqua',
      desc: 'In ultricies condimentum vehicula. Aliquam aliquet placerat mauris vitae lacinia. Nulla facilisi. Nunc et velit sit amet ipsum maximus posuere.',
      category: 'tshirts',
      price: 59,
      image: 'src=../../images/Products/tshirts/tshirtAqua.png',
      sale: true,
      featured: false,
    },
    {
      id: '20',
      name: 'T-shirt Blue',
      desc: 'Cras sit amet gravida velit. Integer vel metus fringilla metus dignissim euismod. Etiam sodales, sem id accumsan tincidunt, est lacus.',
      category: 'tshirts',
      price: 49,
      image: 'src=../../images/Products/tshirts/tshirtBlue.png',
      sale: false,
      featured: true,
    },
    {
      id: '21',
      name: 'T-shirt Green',
      desc: 'Integer porta lobortis ex. Fusce posuere neque eleifend nulla imperdiet sollicitudin. Phasellus leo ex, molestie id consectetur vel, sollicitudin vel.',
      category: 'tshirts',
      price: 69,
      image: 'src=../../images/Products/tshirts/tshirtGreen.png',
      sale: false,
      featured: false,
    },
    {
      id: '22',
      name: 'T-shirt Grey',
      desc: 'Donec ut ex vel augue tempus porta ac ultrices erat. Praesent venenatis tempus massa nec bibendum. Suspendisse potenti. In hac.',
      category: 'tshirts',
      price: 59,
      image: 'src=../../images/Products/tshirts/tshirtGrey.png',
      sale: true,
      featured: false,
    },
    {
      id: '23',
      name: 'T-shirt Orange',
      desc: 'Phasellus vehicula eros non risus lacinia, vel blandit tortor semper. Vestibulum lorem quam, gravida vel libero sit amet, blandit tempus.',
      category: 'tshirts',
      price: 69,
      image: 'src=../../images/Products/tshirts/tshirtOrange.png',
      sale: false,
      featured: false,
    },
    {
      id: '24',
      name: 'T-shirt Pink',
      desc: 'Mauris varius nec eros quis dignissim. Etiam ut consequat elit, eget volutpat quam. Nullam turpis est, gravida ac maximus quis.',
      category: 'tshirts',
      price: 49,
      image: 'src=../../images/Products/tshirts/tshirtPink.png',
      sale: false,
      featured: true,
    },
    {
      id: '25',
      name: 'T-shirt Purple',
      desc: 'Pellentesque et faucibus turpis. Ut vel sapien et lectus facilisis auctor nec vitae sem. Donec venenatis tempor tortor, ut egestas.',
      category: 'tshirts',
      price: 79,
      image: 'src=../../images/Products/tshirts/tshirtPurple.png',
      sale: false,
      featured: false,
    },
    {
      id: '26',
      name: 'T-shirt Red',
      desc: 'Nullam pretium dui et gravida eleifend. Sed ac arcu ut dui pellentesque hendrerit quis eget quam. Nulla lobortis placerat vulputate.',
      category: 'tshirts',
      price: 59,
      image: 'src=../../images/Products/tshirts/tshirtRed.png',
      sale: false,
      featured: false,
    },
    {
      id: '27',
      name: 'T-shirt Yellow',
      desc: 'Etiam ac facilisis felis. Etiam ullamcorper auctor elit, quis mattis nulla finibus in. Pellentesque rhoncus venenatis consectetur. Phasellus diam quam.',
      category: 'tshirts',
      price: 49,
      image: 'src=../../images/Products/tshirts/tshirtYellow.png',
      sale: false,
      featured: false,
    },
  ],
};
